# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 6, 19, 33, 14, 573398, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
